# Generated by Django 4.1 on 2022-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.TextField(unique=True)),
                ("phone", models.TextField()),
                ("password1", models.TextField()),
                ("rdate", models.TextField()),
                ("udate", models.DateTimeField()),
            ],
        ),
    ]
