# Generated by Django 4.1 on 2022-08-11 16:04

import campapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("hits", models.IntegerField(default=0)),
                ("rdate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("email", models.TextField(max_length=60, unique=True)),
                ("phone", models.TextField(primary_key=True, serialize=False)),
                ("password1", models.TextField(max_length=40)),
                ("rdate", models.DateTimeField()),
                ("udate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=200)),
                ("subject", models.TextField(null=True)),
                ("content", models.TextField()),
                ("count", models.IntegerField(default=0)),
                (
                    "upload_files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=campapp.models.get_file_path,
                        verbose_name="파일",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=campapp.models.date_upload_to
                    ),
                ),
                ("top_fixed", models.BooleanField(default=False)),
                ("rdate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Board_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("rdate", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="campapp.board",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campapp.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campapp.member",
            ),
        ),
    ]
