# Generated by Django 4.1 on 2022-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=200)),
                ("subject", models.TextField(null=True)),
                ("content", models.TextField()),
                ("count", models.IntegerField()),
                ("rdate", models.DateTimeField()),
            ],
        ),
    ]
