# Generated by Django 4.1 on 2022-08-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0002_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
