# Generated by Django 4.1 on 2022-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0004_alter_member_rdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="top_fixed",
            field=models.BooleanField(default=False),
        ),
    ]
