# Generated by Django 4.1 on 2022-08-08 12:23

import campapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0005_notice_top_fixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="filename",
            field=models.CharField(max_length=64, null=True, verbose_name="첨부파일명"),
        ),
        migrations.AddField(
            model_name="notice",
            name="upload_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=campapp.models.get_file_path,
                verbose_name="파일",
            ),
        ),
    ]
