# Generated by Django 4.1 on 2022-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0007_remove_notice_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="filename",
            field=models.CharField(max_length=64, null=True, verbose_name="첨부파일명"),
        ),
    ]
