# Generated by Django 4.1 on 2022-08-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0008_notice_filename"),
    ]

    operations = [
        migrations.RemoveField(model_name="notice", name="filename",),
    ]
