# Generated by Django 4.0.6 on 2022-08-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0013_alter_member_email_alter_member_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
