# Generated by Django 4.0.6 on 2022-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0014_remove_member_id_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
