# Generated by Django 4.1 on 2022-08-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0006_notice_filename_notice_upload_files"),
    ]

    operations = [
        migrations.RemoveField(model_name="notice", name="filename",),
    ]
