# Generated by Django 4.1 on 2022-08-08 17:33

import campapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0009_remove_notice_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="photo",
            field=models.ImageField(default=1, upload_to=campapp.models.date_upload_to),
            preserve_default=False,
        ),
    ]
