# Generated by Django 4.1 on 2022-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campapp", "0011_alter_notice_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("hits", models.IntegerField(default=0)),
                ("rdate", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="notice", name="count", field=models.IntegerField(default=0),
        ),
    ]
