# Generated by Django 4.0.6 on 2022-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soobinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=210)),
                ('b_email', models.TextField()),
                ('b_title', models.CharField(max_length=300)),
                ('b_content', models.CharField(max_length=1000)),
                ('b_rdate', models.DateTimeField()),
            ],
        ),
    ]
