# Generated by Django 4.0.6 on 2022-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soobinapp', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('m_email', models.TextField(unique=True)),
                ('m_pwd', models.CharField(max_length=250)),
                ('m_phone', models.CharField(max_length=100)),
                ('m_rdate', models.DateTimeField()),
                ('m_udate', models.DateTimeField()),
            ],
        ),
    ]
